### ISSUE TITLE
What raw data should be exportable?

### ISSUE THREAD

**Issue by mkuzak** [andi-nl/andi#4]
https://github.com/andi-nl/andi/blob/master/requirements-2016-04-18.md#raw-data-should-be-exportable-as-well
what exactly is the data that needs to be exported?

**Comment by Nanouk123** [comment]
Once clinicians have entered all data in the form (so for each patient(s)) they should be able to export a file (for example csv) with these data. If the next time they want to view this patient again they will upload the file instead of of typing in the data by hand. Perhaps even easier is when you make an export you automatically dld a file (word, pdf?) with the results (the graphs etc.) and the csv.
